language: python
python:
  - 2.7

install:
  - pip install -r pip-requires --use-mirrors
  - pip install pep8

before_script:
  - psql -c "CREATE DATABASE popcorn;" -U postgres
  - psql -c "CREATE USER popcorn WITH PASSWORD 'popcorn';" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE popcorn TO popcorn;" -U postgres

script:
  - pep8 popcorn
  - python setup.py test
